# Generated by Django 5.2.14 on 2026-05-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=24)),
                ('status', models.CharField(default='started', max_length=24)),
                ('external_id', models.CharField(blank=True, max_length=140)),
                ('customer_name', models.CharField(blank=True, max_length=160)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('items', models.JSONField(blank=True, default=list)),
                ('amount_cents', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='usd', max_length=8)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
