# Generated by Django 5.2.14 on 2026-05-10 23:24

from django.db import migrations, models


def create_test_coupon(apps, schema_editor):
    Coupon = apps.get_model("showcase", "Coupon")
    Coupon.objects.update_or_create(
        code="TEST30",
        defaults={"percent_off": 30, "is_active": True},
    )


def remove_test_coupon(apps, schema_editor):
    Coupon = apps.get_model("showcase", "Coupon")
    Coupon.objects.filter(code="TEST30").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('percent_off', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.RunPython(create_test_coupon, remove_test_coupon),
    ]
